
-- Criação do banco de dados
CREATE DATABASE M01S07_NORM

USE M01S07_NORM

--DROP DATABASE M01S07_NORM


-- Criação da tabela funcionario
CREATE TABLE FUNCIONARIO(
   ID INT IDENTITY (1,1) PRIMARY KEY,
   NOME VARCHAR(50),
   CARGO VARCHAR(50),
   TELEFONE1 VARCHAR(11),
   TELEFONE2 VARCHAR(11)
)

-- DROP TABLE FUNCIONARIO


-- Primeira forma normal
CREATE TABLE FUNCIONARIO_FN1(
   ID INT IDENTITY (1,1) PRIMARY KEY,
   NOME VARCHAR(50),
   CARGO VARCHAR(50)
)

CREATE TABLE TELEFONE_FN1(
   ID INT REFERENCES FUNCIONARIO_FN1(ID) NOT NULL,
   TELEFONE VARCHAR(11) NOT NULL
)

ALTER TABLE TELEFONE_FN1 ADD PRIMARY KEY (ID, TELEFONE)

-- DROP TABLE FUNCIONARIO_FN1
-- DROP TABLE TELEFONE_FN1


-- Segunda forma normal
CREATE TABLE FUNCIONARIO_FN2(
  ID INT IDENTITY (1,1) PRIMARY KEY,
  NOME VARCHAR(50)
)

CREATE TABLE ALOCACAO_FN2(
  ID INT REFERENCES FUNCIONARIO_FN2(ID) NOT NULL,
  CARGO VARCHAR(50)
)

ALTER TABLE ALOCACAO_FN2 ADD PRIMARY KEY (ID, CARGO)

CREATE TABLE TELEFONE_FN2(
   ID INT REFERENCES FUNCIONARIO_FN2(ID) NOT NULL,
   TELEFONE VARCHAR(11) NOT NULL
)

ALTER TABLE TELEFONE_FN2 ADD PRIMARY KEY (ID, TELEFONE)

-- DROP TABLE FUNCIONARIO_FN2
-- DROP TABLE ALOCACAO_FN2
-- DROP TABLE TELEFONE_FN2


-- Terceira forma normal
CREATE TABLE CARGO_FN3(
   ID INT IDENTITY (1,1) PRIMARY KEY, 
   CARGO VARCHAR(50)
)

CREATE TABLE FUNCIONARIO_FN3(
  ID INT IDENTITY (1,1) PRIMARY KEY,
  NOME VARCHAR(50)
)

CREATE TABLE ALOCACAO_FN3(
  FUNCIONARIO_ID INT REFERENCES FUNCIONARIO_FN3(ID) NOT NULL,
  CARGO_ID INT REFERENCES CARGO_FN3(ID) NOT NULL
)

ALTER TABLE ALOCACAO_FN3 ADD PRIMARY KEY (FUNCIONARIO_ID, CARGO_ID)

CREATE TABLE TELEFONE_FN3(
   ID INT REFERENCES FUNCIONARIO_FN3(ID) NOT NULL,
   TELEFONE VARCHAR(11) NOT NULL
)

ALTER TABLE TELEFONE_FN3 ADD PRIMARY KEY (ID, TELEFONE)

-- DROP TABLE CARGO_FN3
-- DROP TABLE FUNCIONARIO_FN3
-- DROP TABLE ALOCACAO_FN3
-- DROP TABLE TELEFONE_FN3


-- Inclusão de registros
INSERT INTO CARGO_FN3 (CARGO) VALUES ('Atendente'),('Gerente')

INSERT INTO FUNCIONARIO_FN3 (NOME) VALUES ('Marcos'),('Maria'),('Julia')

INSERT INTO ALOCACAO_FN3 VALUES (1, 1), (2, 2), (3, 1)

INSERT INTO TELEFONE_FN3 VALUES (1, '3654589'),(2, '3654698'), (3, '3654962')

INSERT INTO TELEFONE_FN3 VALUES (1, '36545987'),(2, '36524569'), (3, '12365458')


-- Seleção de registros
SELECT * FROM FUNCIONARIO_FN3
JOIN TELEFONE_FN3 ON FUNCIONARIO_FN3.ID = TELEFONE_FN3.ID

SELECT * FROM FUNCIONARIO_FN3
JOIN ALOCACAO_FN3 ON FUNCIONARIO_FN3.ID = ALOCACAO_FN3.FUNCIONARIO_ID

SELECT * FROM CARGO_FN3
JOIN ALOCACAO_FN3 ON CARGO_FN3.ID = ALOCACAO_FN3.CARGO_ID

SELECT * FROM FUNCIONARIO_FN3

SELECT * FROM CARGO_FN3

